singleServerConfig:
  address: redis://127.0.0.1:6379

---

spring:
  application:
    name: Challenge
  datasource:
    driver-class-name: org.postgresql.Driver
    username: rv_user
    password: rv_password
    url: jdbc:postgresql://localhost:5432/postgres_rv_database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        javax:
          cache:
            uri: application.yml
        cache:
          region:
            factory_class: jcache
          use_second_level_cache: true